services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Markocupic\ContaoSchuleEttiswilLicensesBundle\Controller\FrontendModule\SchuleEttiswilLicensesListModuleController:
        arguments:
            - '@database_connection'
            - '@twig'
        tags:
            - { name: contao.frontend_module, category: schule_ettiswil, template: mod_schule_ettiswil_licenses_list_module, type: schule_ettiswil_licenses_list_module }
        public: true

    Markocupic\ContaoSchuleEttiswilLicensesBundle\ExportData\Excel: ~
